import type { SessionConfig } from "../config";
import type { VoiceProviderStatus } from "./voice-provider";

export interface RuntimeCapability {
  provider: string;
  mode: string;
  note: string;
}

export interface PersistenceCapability extends RuntimeCapability {
  durable: boolean;
}

export interface RuntimeCapabilities {
  storage: PersistenceCapability;
  queue: PersistenceCapability;
  voice: RuntimeCapability;
  ai: RuntimeCapability;
  warnings: string[];
}

export function buildRuntimeCapabilities(config: SessionConfig, voice: VoiceProviderStatus): RuntimeCapabilities {
  const storage: PersistenceCapability = {
    provider: "memory",
    mode: "in-memory",
    durable: false,
    note: "Session rooms and ledgers live inside the process. Restarting the service resets canonical state."
  };

  const queue: PersistenceCapability = {
    provider: "memory",
    mode: "in-process",
    durable: false,
    note: "Outbox jobs run from an in-process queue. Worker state is not durable across restarts."
  };

  const ai: RuntimeCapability =
    config.AI_PROVIDER === "openai"
      ? {
          provider: "openai",
          mode: "needs-config",
          note: "OpenAI was selected, but the scaffold still uses a deterministic local copilot response path."
        }
      : {
          provider: "mock",
          mode: "mock",
          note: "AI suggestions are generated by the local mock copilot service in this scaffold."
        };

  const warnings: string[] = [];

  if (config.DATABASE_URL) {
    warnings.push("DATABASE_URL is configured, but the session service still boots the in-memory RoomStore.");
  }

  if (config.REDIS_URL) {
    warnings.push("REDIS_URL is configured, but the outbox still runs on an in-process queue.");
  }

  if (voice.mode === "needs-config") {
    warnings.push(voice.note);
  }

  if (config.AI_PROVIDER === "openai") {
    warnings.push(ai.note);
  }

  return {
    storage,
    queue,
    voice,
    ai,
    warnings
  };
}
